config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  d_spacemacs.d:
    src: spacemacs.d
    dst: ~/.spacemacs.d
    upignore:
      - ".spacemacs.env"
profiles:
  HomeWin10:
    dotfiles:
    - f_bash_profile
    - f_bashrc
    - d_spacemacs.d
