config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
profiles:
  HomeWin10:
    dotfiles:
    - f_bash_profile
    - f_bashrc
